"""Build the static dashboard site from the stored datasets.

Renders a single self-contained ``site/index.html`` (plus a copied stylesheet
and the CSV downloads) using Jinja2 and the Plotly figures. Plotly's JS is
loaded from the CDN by default but can be vendored for fully-offline builds.

The build is deterministic given the datasets and performs no network calls
(other than the browser later fetching the Plotly CDN script). It degrades
gracefully when only a single day of data exists.
"""

from __future__ import annotations

import datetime as dt
import os
import shutil
from pathlib import Path
from typing import Any

import plotly.io as pio
from jinja2 import Environment, FileSystemLoader, select_autoescape
from markupsafe import Markup

from ..config import PATHS, Paths
from ..logging_utils import get_logger
from ..storage.datasets import DatasetStore
from . import figures as F

logger = get_logger(__name__)

_TEMPLATE_DIR = Path(__file__).resolve().parent / "templates"
PLOTLY_CDN = "https://cdn.plot.ly/plotly-2.35.2.min.js"

# Libraries/metrics highlighted in the multi-series charts.
_TREND_LIBRARIES = [
    "pandas",
    "numpy",
    "matplotlib",
    "scikit_learn",
    "pytorch",
    "tensorflow",
    "plotly",
    "seaborn",
    "marimo",
    "ipywidgets",
]


def _fig_div(fig: Any) -> Markup:
    """Convert a Plotly figure to an embeddable, responsive div (no full HTML).

    Returned as :class:`markupsafe.Markup` so Jinja2 (autoescape on) inserts the
    Plotly ``<div>``/``<script>`` verbatim instead of HTML-escaping it. The
    content is generated by Plotly from our own trusted figures, not from
    user-supplied data, so marking it safe is correct.
    """
    html: str = pio.to_html(
        fig,
        include_plotlyjs=False,
        full_html=False,
        config={"displayModeBar": False, "responsive": True},
    )
    return Markup(html)


def _stat_cards(
    current: Any, current_adopt: Any, repo_url: str, all_snaps: Any
) -> list[dict[str, str]]:
    latest = current.sort_values("run_date").iloc[-1]
    latest_date = latest["run_date"]
    # All-time total spans every collection mode (daily + cohort backfill).
    total_collected = int(all_snaps["notebooks_collected"].sum())
    latest_adopt = current_adopt[current_adopt["run_date"] == latest_date]
    top = (
        latest_adopt.sort_values("adoption_pct", ascending=False).iloc[0]
        if len(latest_adopt)
        else None
    )
    cards = [
        {
            "value": f"{total_collected:,}",
            "label": "Notebooks observed (all time)",
            "sub": f"+{int(latest['notebooks_collected'])} today",
        },
        {
            "value": f"{int(latest['notebooks_parsed'])}",
            "label": "Parsed in latest run",
            "sub": f"{latest['parse_success_rate'] * 100:.0f}% parse success",
        },
        {
            "value": f"{latest.get('reproducibility_score_mean', 0) * 100:.0f}%",
            "label": "Mean reproducibility",
            "sub": "",
        },
        {
            "value": (top["library"] if top is not None else "—"),
            "label": "Most-used library",
            "sub": (f"{top['adoption_pct']:.0f}% of notebooks" if top is not None else ""),
        },
    ]
    return cards


def build_site(
    paths: Paths | None = None,
    repo_url: str | None = None,
    agent_space_url: str | None = None,
) -> Path:
    """Render the static dashboard into ``site/``.

    Args:
        paths: Filesystem layout (defaults to the package config).
        repo_url: Canonical repository URL for links.
        agent_space_url: Embed URL of the Hugging Face Space hosting the Q&A
            agent. Defaults to the ``NBOBS_AGENT_SPACE_URL`` env var, then the
            project's published Space. Pass an empty string to render the
            "being provisioned" placeholder instead of the iframe.

    Returns:
        Path to the generated ``index.html``.

    Raises:
        RuntimeError: if no daily snapshots exist yet (nothing to render).
    """
    paths = paths or PATHS
    repo_url = repo_url or "https://github.com/rodrigosf672/notebook-observatory"
    if agent_space_url is None:
        agent_space_url = os.environ.get(
            "NBOBS_AGENT_SPACE_URL",
            "https://rodrigosf672-notebook-observatory-agent.hf.space",
        )
    store = DatasetStore(paths)

    snapshots = store.read_daily_snapshots()
    adoption = store.read_library_adoption()
    if snapshots.empty:
        raise RuntimeError("No daily snapshots found; run a collection first.")

    paths.site.mkdir(parents=True, exist_ok=True)

    # Split the two collection modes. "cohort" rows are the historical
    # creation-year backfill (2013..present) and form the real longitudinal
    # series; "daily" rows are the live daily census. Older snapshots without a
    # collection_type are treated as daily.
    if "collection_type" not in snapshots.columns:
        snapshots["collection_type"] = "daily"
    if "collection_type" not in adoption.columns:
        adoption["collection_type"] = "daily"
    cohort_snaps = snapshots[snapshots["collection_type"] == "cohort"].sort_values("run_date")
    daily_snaps = snapshots[snapshots["collection_type"] == "daily"].sort_values("run_date")
    cohort_adopt = adoption[adoption["collection_type"] == "cohort"]
    daily_adopt = adoption[adoption["collection_type"] == "daily"]

    # The adoption-trend chart prefers the multi-year cohort series; the daily
    # series drives current-state cards. Fall back to daily if no cohorts.
    trend_adopt = cohort_adopt if not cohort_adopt.empty else daily_adopt
    current_snaps = daily_snaps if not daily_snaps.empty else snapshots
    current_adopt = daily_adopt if not daily_adopt.empty else adoption
    has_cohorts = not cohort_snaps.empty

    # Build figures. The dashboard visualizes library adoption directly; the
    # broader structural, quality, and Python-version detail (which had its own
    # charts before) is folded into the agent's grounding data, so the "Ask the
    # observatory" section can answer those questions from real numbers.
    figs = {
        "ranking": _fig_div(F.library_adoption_ranking(current_adopt)),
        "adoption_trend": _fig_div(F.library_adoption_trends(trend_adopt, _TREND_LIBRARIES)),
    }

    # Library table (latest daily run, top 20).
    latest_date = current_snaps.sort_values("run_date").iloc[-1]["run_date"]
    latest_adopt = (
        current_adopt[current_adopt["run_date"] == latest_date]
        .sort_values("adoption_pct", ascending=False)
        .head(20)
    )
    library_table = [
        {
            "library": r["library"],
            "category": r["category"],
            "adoption_pct": float(r["adoption_pct"]),
            "notebook_count": int(r["notebook_count"]),
            "color": F.CATEGORY_COLORS.get(r["category"], "#8899A6"),
        }
        for _, r in latest_adopt.iterrows()
    ]

    # Copy CSV downloads into the site so Pages can serve them directly.
    for src in (paths.daily_snapshots_csv, paths.library_adoption_csv):
        if src.exists():
            shutil.copy2(src, paths.site / src.name)

    css = (_TEMPLATE_DIR / "style.css").read_text(encoding="utf-8")

    env = Environment(
        loader=FileSystemLoader(str(_TEMPLATE_DIR)),
        autoescape=select_autoescape(["html", "xml", "j2"]),
    )
    template = env.get_template("index.html.j2")
    html = template.render(
        inline_css=Markup(css),
        plotly_src=PLOTLY_CDN,
        repo_url=repo_url,
        generated_at=dt.datetime.now(dt.UTC).strftime("%Y-%m-%d %H:%M UTC"),
        latest_date=latest_date,
        agent_space_url=agent_space_url,
        n_days=int(daily_snaps["run_date"].nunique()) if not daily_snaps.empty else 0,
        n_cohorts=int(cohort_snaps["run_date"].nunique()),
        has_cohorts=has_cohorts,
        cohort_span=(
            f"{cohort_snaps['run_date'].min()[:4]}–{cohort_snaps['run_date'].max()[:4]}"
            if has_cohorts
            else ""
        ),
        stat_cards=_stat_cards(current_snaps, current_adopt, repo_url, snapshots),
        figures=figs,
        library_table=library_table,
        data_links={
            "snapshots_csv": paths.daily_snapshots_csv.name,
            "adoption_csv": paths.library_adoption_csv.name,
        },
    )
    out = paths.site / "index.html"
    out.write_text(html, encoding="utf-8")
    # .nojekyll so GitHub Pages serves files starting with underscores etc.
    (paths.site / ".nojekyll").write_text("", encoding="utf-8")
    logger.info("Dashboard written to %s (%d KB)", out, len(html) // 1024)
    return out
